### PR TITLE
Create Create How to Use

### PR DESCRIPTION
**Pull request by sudheerbabuu**
++ How to Use File
++ Self Configuration steps

### CODE REVIEW

**Comment by SudheerBabu-Sr** [comment]
++ How to Use File
++ Self Configuration steps

**Comment by SudheerBabu-Sr** [comment]
++ How to Use File
++ Self Configuration steps

**Comment by h3ct0rjs** [comment]
@binhnguyennus we can proceed to close this PR.

**Review by ArnavK-09 — CHANGES_REQUESTED** [review]
?

**Review by mosibani — CHANGES_REQUESTED** [review]
Let's stert as the teems

**Pull request closed without merging**
