### PR TITLE
improvement: Github Action to Markdown link checker

### PR DESCRIPTION
**Pull request by olivierodo**
Hello @binhnguyennus ,
I came across your AMAZING repo and after clicking in a few links I came through a few invalid links...
Then allow me to propose a Github action that would be able to detect the if a link is dead or not 😅.

The Github action used is https://github.com/marketplace/actions/404-links

Let me know if you have any question.

### CODE REVIEW

**Comment by olivierodo** [comment]
After running the action on my fork here is the result:
image


link: https://github.com/olivierodo/awesome-scalability/actions/runs/3996565484

**Comment by olivierodo** [comment]
Since i don't know if this PR will remain stale or not i didn't put the effort on cleaning the dead link yet.
But if you are interested, please comment and I will finalize the PR.

**Comment by olivierodo** [comment]
Gotcha, thanks for the feedback

**Review by VickyPascale — COMMENTED** [review]
Non authauriser

**Pull request closed without merging**
