### PR TITLE
add "Life Beyond Distributed Transactions"

### PR DESCRIPTION
**Pull request by nwalker**
excerpt: 

"Transactions are amazingly powerful mechanisms, and I've spent the majority of my almost 40-year career working on them. In 1982, I first worked to provide transactions on the Tandem NonStop System. This system had a mean time between failures measured in years and included a geographically distributed two-phase commit offering excellent availability for strongly consistent transactions.

New innovations, including Google's Spanner, offer strongly consistent transactional environments at extremely large scale with excellent availability. Building distributed transactions to support highly available applications is a great challenge that has inspired excellent innovation and great technology. Unfortunately, this is not broadly available to application developers.

...

This article explores and names some of the practical approaches used in the implementation of large-scale mission-critical applications in a world that rejects distributed transactions."

### CODE REVIEW

**Comment by binhnguyennus** [comment]
Hi,

Could you please point out the link that you want to add, and in which section?

However, as I stated in the Introduction, this project was initiated to illustrate Scalability, Availability, and Stability Design Patterns in Back-end Development. The readers I target is Software Engineers who want to find ideas for their practical works, as well as and people who are preparing for a System Design interview.

Hence, things those are too academic may not so suitable here :)

Best regards,
Benny

**Comment by nwalker** [comment]
Hi, Benny. 

> Could you please point out the link that you want to add, and in which section?

[Link](https://queue.acm.org/detail.cfm?id=3025012). 
I propose it for "Principles" section, because it is not specific enough for others. I thinked about placing it in "scalability" but I was unable to select subsection. Any advice will be appreciated.

> Hence, things those are too academic may not so suitable here :)

I don't think it is too academic. It may be not practical enough, but IMO it is worth reading. Anyway it is only my opinion, so I recommend you to give it at least quick look to get yours. 

For me it was really enlightening read when I searched for queue-based SOA design patterns. For some other guy it will be "not practical enough".

**Comment by binhnguyennus** [comment]
OMG, this paper is such a gem! I have just added it. Btw, do you have any suggestion on how to make my list better? Anymore sections need to be added or something should be changed?

Thanks you so much!

**Comment by nwalker** [comment]
> OMG, this paper is such a gem!

Glad you liked it. 

> any suggestion 

Sorry, I can't think of any good changes. Or maybe one - to remove "Mnesia: A Distributed DBMS Rooted in Concurrency" link. This article does not highlight any of mnesia cons and mnesia has ton of them. 

I doing Erlang for last 6 years, so I know a bit about it, and there is point wide spread in Erlang community - "do not use mnesia unless you know what you doing". mnesia just can't compete with modern DBMS solutions in terms of bot consistency and availability - it can't handle netsplits, it uses slow to recover file backend. Last but not least, it lacks maintainability - no tools, nearly zero people understand how to manage it.

**Comment by binhnguyennus** [comment]
Hi,

Your comment about Mnesia is valuable! I also think that article does not emphasize the Pros and Cons. However it somehow triggers some thoughts about handling concurrency, then I will keep it at the moment. Well, Erlang and Mnesia are widely used in Sweden (due to Ericsson) then the good reference sources usually in Swedish. I am trying to find a better source one to replace that link.

Thanks and have a good weekend!
Benny

**Pull request closed without merging**
